---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - name: i want to install websever 
      apt:
        name: apache2
        state: present

    - name: i want to install tree
      apt:
        name: tree
        state: present 